### ISSUE TITLE
Field length of custom Fields in SQL is only 1 Char but TCA defintion is 80 chars 

### ISSUE THREAD

**Issue by velletti** [evoWeb/ew_sfregister_extended#1]
just need to change ext_tables.sql form varchar(1) to varchar(80)

**Comment by velletti** [comment]
i cahnged rxt_tables.sql lke this:
#

# Table structure for table 'fe_users'

#
CREATE TABLE fe_users (
    custom0 varchar(80) DEFAULT '',
    custom1 varchar(80) DEFAULT '',
    custom2 varchar(80) DEFAULT '',
    custom3 varchar(80) DEFAULT '',
    custom4 varchar(80) DEFAULT '',
    custom5 varchar(80) DEFAULT '',
    custom6 varchar(80) DEFAULT '',
    custom7 varchar(80) DEFAULT '',
    custom8 varchar(80) DEFAULT '',
    custom9 varchar(80) DEFAULT ''
);

**Comment by garbast** [comment]
Changed the ext_tables.sql
